# Generated by Django 4.2.5 on 2023-09-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task1'),
    ]

    operations = [
        migrations.AddField(
            model_name='task1',
            name='date',
            field=models.DateField(default='1993-04-23'),
            preserve_default=False,
        ),
    ]
